config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :players
  get "blackjacks/main"
  get "blackjacks/topten"
  resources :blackjacks

  match "api/gameusers/topten", to: 'gameusers#topten', via: 'get'
  match "api/gameusers/getuser", to: 'gameusers#getuser', via: 'get'

  scope "api" do
    resources :blackjacks
    resources :gameusers
  end

  get "kidcomments/new"
  get "kidcomments/index"
  get "kidcomments/destroy"
  get "kids/new"
  get "kids/update"
  get "kids/show"
  get "kids/index"
  get 'tags/:tag', to: 'kids#index', as: :tag
  resources :kids
  resources :users
  resources :users do
	member do
		get :following, :followers
	end
  end
  resources :kidcomments, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match '/kid_comments',    to: 'kidcomments#create',    via: 'post'

  match '/report',  to: 'kids#new',            via: 'get'

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/blackjack.rb
class Blackjack < ActiveRecord::Base
        belongs_to :holder , {class_name: :User, foreign_key: 'holder'}
        belongs_to :attender , {class_name: :User, foreign_key: 'attender'}
        belongs_to :winner , {class_name: :User, foreign_key: 'winner'}
end

app/models/kid.rb
class Kid < ActiveRecord::Base
	belongs_to :user
	has_many :kid_comments, dependent: :destroy
	#has_many :kid_places, dependent: :destroy
	#has_many :place_tags, through: :kid_places

	#validates :age, presence: true
	#,  numericality: true, inclusion: { in: 0..17 }
	#validates :gender, inclusion: %w(Male Female), allow_nil: true

	acts_as_taggable
	acts_as_taggable_on :places, :appearances

end

app/models/kid_comment.rb
class KidComment < ActiveRecord::Base
	belongs_to :kid
	belongs_to :user

  def self.user_kid_comments(user)
      where("id in (select id from kid_comments where kid_id in (select id from kids where user_id=:user_id) )",user_id: user.id)
  end
end

app/models/kid_place.rb
class KidPlace < ActiveRecord::Base
	belongs_to :kid
	belongs_to :place_tag
end

app/models/kid_tag.rb
class KidTag < ActiveRecord::Base
	belongs_to :kid
	belongs_to :tag
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  def self.from_users_followed_by(user)
	where("user_id in (select followed_id from relationships where follower_id = :user_id) or user_id=:user_id",user_id: user.id)
  end
end

app/models/place_tag.rb
class PlaceTag < ActiveRecord::Base
	has_many :kid_places
	has_many :kids, through: :kid_places
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	# belongs_to :tag_type
	has_many :kid_tags
	has_many :kids, through: :kid_tags
end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
	# has_many :tags
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :task_type
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
	has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
has_many :relationships, foreign_key: "follower_id", dependent: :destroy
has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :kids, dependent: :destroy
  has_many :kid_comments, dependent: :destroy

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password

def title
      t=""
      if self.score.nil? || self.credit<2000
         t="Pool "
      else
         t="Rich "
      end

      if self.score.nil? || self.score<2000
        t+="Patrolmen"
      else
        t+="Sheriff"
      end
  end


  def my_kid_comments
      KidComment.user_kid_comments(self)
  end

  def feed
	Micropost.from_users_followed_by(self)
  end

  def self.new_remember_token
	SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
	Digest::SHA1.hexdigest(token.to_s)
  end

  def following?(other_user)
	relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
	relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

	private

  def create_remember_token
	self.remember_token=User.encrypt(User.new_remember_token)
  end

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
	if signed_in?    
		@micropost = current_user.microposts.build
		@feed_items=current_user.feed.paginate(page: params[:page])
        @kidcomments=current_user.my_kid_comments.paginate(page: params[:page])
	end
  end

  def help
  end

  def about
  end
  
  def contact
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
	base_title = "Finding Kid"
	if page_title.empty?
	base_title
	else
	"#{base_title} | #{page_title}"
	end
  end 

end

app/helpers/blackjacks_helper.rb
module BlackjacksHelper
end

app/helpers/kidcomments_helper.rb
module KidcommentsHelper
end

app/helpers/kids_helper.rb
module KidsHelper

  def kid_picture(kid, options = { size: 50 })
    base_path="pictures"
    image_path="#{base_path}/no_image.png"
    if !kid.picture.empty?
      image_path="#{base_path}/#{kid.picture}"
    end
    size = options[:size]
    image_tag(image_path, width: size, height: size, alt: kid.name, class: "gravatar")
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def current_user?(user)
    current_user==user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user=nil
    cookies.delete(:remember_token)   
  end

    def signed_in_user
        if !signed_in?
                store_location
                redirect_to signin_url, notice: "Please sign in."
        end
    end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://s.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= link_to "Report Kid", report_path,
                                class: "btn btn-large btn-primary" %>
        <%= link_to "Find Kid", kids_path,
                                class: "btn btn-large btn-primary" %>
      </section>
      <section>
        Finsh tasks to earn credits</b>
        <p><a href="#">Facebook</a></p>
      </section>
    </aside>
    <div class="span8">
      <h3>Latest comments for my kid</h3>
            <ol class="microposts">
      <%= render @kidcomments %>
    </ol>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to Finding Kid</h1>

    <h2>
      Helping the lost child find home
    </h2>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>