config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :players
  get "blackjacks/main"
  get "blackjacks/topten"
  resources :blackjacks

  match "api/gameusers/topten", to: 'gameusers#topten', via: 'get'
  match "api/gameusers/getuser", to: 'gameusers#getuser', via: 'get'

  scope "api" do
    resources :blackjacks
    resources :gameusers
  end

  get "kidcomments/new"
  get "kidcomments/index"
  get "kidcomments/destroy"
  get "kids/new"
  get "kids/update"
  get "kids/show"
  get "kids/index"
  get 'tags/:tag', to: 'kids#index', as: :tag
  resources :kids
  resources :users
  resources :users do
	member do
		get :following, :followers
	end
  end
  resources :kidcomments, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match '/kid_comments',    to: 'kidcomments#create',    via: 'post'

  match '/report',  to: 'kids#new',            via: 'get'

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/kid.rb
class Kid < ActiveRecord::Base
	belongs_to :user
	has_many :kid_comments, dependent: :destroy
	#has_many :kid_places, dependent: :destroy
	#has_many :place_tags, through: :kid_places

	#validates :age, presence: true
	#,  numericality: true, inclusion: { in: 0..17 }
	#validates :gender, inclusion: %w(Male Female), allow_nil: true

	acts_as_taggable
	acts_as_taggable_on :places, :appearances

end

app/controllers/kids_controller.rb
class KidsController < ApplicationController

	before_action :signed_in_user
  	before_action :correct_user, only: [:edit, :update, :destroy]
  def new
  	@kid=Kid.new
  end

  def edit
	@kid=Kid.find(params[:id])
  end

  def destroy
    Kid.find(params[:id]).destroy
    flash[:success]="Deleted Kid"
    redirect_to kids_url
  end

  def show
    @kid = Kid.find(params[:id])
    @kidcomment=@kid.kid_comments.build
    @kidcomments = @kid.kid_comments.paginate(page: params[:page])
  end

  def index
  if params[:tag]
    @kids = Kid.tagged_with(params[:tag]).paginate(page: params[:page])
  else
    @kids = Kid.paginate(page: params[:page])
  end
  end

  def create
      @kid =current_user.kids.new(kid_param)
      #@kid.picture = @kid.picture.new(picture_params)
\
      if @kid.save
        flash[:success]="Successful reported kid!" 
	redirect_to kid_path(@kid)
      else
         render 'new'
      end
  end

  private

    def kid_param
      params.require(:kid).permit(:name,:gender,:age,:time, :appearance_list, :place_list, :tags, :picture,:credits,:lost, :picture_file_name)
    end

        def picture_param
      params.require(:kid).permit(:picture, :picture_file_name)
    end

      def correct_user
      @kid = Kid.find(params[:id])
      redirect_to(root_path) unless current_user.kids.find(@kid)    
      end
end

app/helpers/kids_helper.rb
module KidsHelper

  def kid_picture(kid, options = { size: 50 })
    base_path="pictures"
    image_path="#{base_path}/no_image.png"
    if !kid.picture.empty?
      image_path="#{base_path}/#{kid.picture}"
    end
    size = options[:size]
    image_tag(image_path, width: size, height: size, alt: kid.name, class: "gravatar")
  end

end

app/views/kids/_kid.html.erb
<li>
<li>
        <%=kid_picture kid%>
        <%=link_to kid.name, kid %> <% if kid.lost %> (Lost) <% else %> (Waif) <%end%>
	<% if current_user.admin? %>
	 | <%=link_to "delete", kid, method: :delete, data: {confirm: "Delete kid?"} %>
	<% end %>
</li>

app/views/kids/edit.html.erb
<h1>Kids#edit</h1>
<p>Find me in app/views/kids/edit.html.erb</p>

app/views/kids/index.html.erb
<% provide(:title, "All kids") %>
<h1>All kids</h1>

<span id="tag_cloud">
  <% tag_cloud Kid.appearance_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</span>

<div id="tag_cloud">
  <% tag_cloud Kid.place_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<%= will_paginate %>

<ul class="users">

<%= render @kids %>

</ul>

<%= will_paginate %>

app/views/kids/match.html.erb
<h1>Help them go home!</h1>

<table>
<tr>
<td>Lost</td>
<td>Waif</td>
</tr>
<tr>
<td>#</td>
<td>#</td>
</tr>
</table>

app/views/kids/new.html.erb
<% provide(:title, 'Report Kid') %>
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

<h1>Report Kid</h1>

<div class="row">
	<div class="span6 offset3">
	<%= form_for(@kid, :html => { :multipart => true }) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= render 'shared/kid_form', f: f %>
		<%= f.submit "Report Kid", class: "btn btn-large btn-primary" %>
	<% end %>
	</div>
</div>

app/views/kids/show.html.erb
<% provide(:title, @kid.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= kid_picture @kid, size: 150 %>
        <%= @kid.name %> <% if @kid.lost %> (Lost) <% else %> (Waif) <%end%>
      </h1>
    </section>
    <section>
      <span>
        Gender: <%= @kid.gender %>
      </span>
      <span>
        Age: <%= @kid.age %>
      </span>
      <span>
        Appearances: <%= raw @kid.appearance_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </span>    
      <span>
        Places: <%= raw @kid.place_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </span>      
    </section>
  </aside>
    <div class="span8">
      <section>
        <%= render 'shared/kid_comment_form' %>
      </sectin>
    </div>
  <div class="span8">
      <% if @kid.kid_comments.any? %>
      <h3>Comment (<%= @kid.kid_comments.count %>)</h3>
      <ol class="microposts">
        <%= render @kidcomments %>
      </ol>
      <%= will_paginate @kidcomments %>
    <% end %>
  </div>
</div>

app/views/kids/update.html.erb
<h1>Kids#edit</h1>
<p>Find me in app/views/kids/edit.html.erb</p>