config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :players
  get "blackjacks/main"
  get "blackjacks/topten"
  resources :blackjacks

  match "api/gameusers/topten", to: 'gameusers#topten', via: 'get'
  match "api/gameusers/getuser", to: 'gameusers#getuser', via: 'get'

  scope "api" do
    resources :blackjacks
    resources :gameusers
  end

  get "kidcomments/new"
  get "kidcomments/index"
  get "kidcomments/destroy"
  get "kids/new"
  get "kids/update"
  get "kids/show"
  get "kids/index"
  get 'tags/:tag', to: 'kids#index', as: :tag
  resources :kids
  resources :users
  resources :users do
	member do
		get :following, :followers
	end
  end
  resources :kidcomments, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match '/kid_comments',    to: 'kidcomments#create',    via: 'post'

  match '/report',  to: 'kids#new',            via: 'get'

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/blackjack.rb
class Blackjack < ActiveRecord::Base
        belongs_to :holder , {class_name: :User, foreign_key: 'holder'}
        belongs_to :attender , {class_name: :User, foreign_key: 'attender'}
        belongs_to :winner , {class_name: :User, foreign_key: 'winner'}
end

app/models/kid.rb
class Kid < ActiveRecord::Base
	belongs_to :user
	has_many :kid_comments, dependent: :destroy
	#has_many :kid_places, dependent: :destroy
	#has_many :place_tags, through: :kid_places

	#validates :age, presence: true
	#,  numericality: true, inclusion: { in: 0..17 }
	#validates :gender, inclusion: %w(Male Female), allow_nil: true

	acts_as_taggable
	acts_as_taggable_on :places, :appearances

end

app/models/kid_comment.rb
class KidComment < ActiveRecord::Base
	belongs_to :kid
	belongs_to :user

  def self.user_kid_comments(user)
      where("id in (select id from kid_comments where kid_id in (select id from kids where user_id=:user_id) )",user_id: user.id)
  end
end

app/models/kid_place.rb
class KidPlace < ActiveRecord::Base
	belongs_to :kid
	belongs_to :place_tag
end

app/models/kid_tag.rb
class KidTag < ActiveRecord::Base
	belongs_to :kid
	belongs_to :tag
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  def self.from_users_followed_by(user)
	where("user_id in (select followed_id from relationships where follower_id = :user_id) or user_id=:user_id",user_id: user.id)
  end
end

app/models/place_tag.rb
class PlaceTag < ActiveRecord::Base
	has_many :kid_places
	has_many :kids, through: :kid_places
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	# belongs_to :tag_type
	has_many :kid_tags
	has_many :kids, through: :kid_tags
end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
	# has_many :tags
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :task_type
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
	has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
has_many :relationships, foreign_key: "follower_id", dependent: :destroy
has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :kids, dependent: :destroy
  has_many :kid_comments, dependent: :destroy

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password

def title
      t=""
      if self.score.nil? || self.credit<2000
         t="Pool "
      else
         t="Rich "
      end

      if self.score.nil? || self.score<2000
        t+="Patrolmen"
      else
        t+="Sheriff"
      end
  end


  def my_kid_comments
      KidComment.user_kid_comments(self)
  end

  def feed
	Micropost.from_users_followed_by(self)
  end

  def self.new_remember_token
	SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
	Digest::SHA1.hexdigest(token.to_s)
  end

  def following?(other_user)
	relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
	relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

	private

  def create_remember_token
	self.remember_token=User.encrypt(User.new_remember_token)
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
	base_title = "Finding Kid"
	if page_title.empty?
	base_title
	else
	"#{base_title} | #{page_title}"
	end
  end 

end

app/helpers/blackjacks_helper.rb
module BlackjacksHelper
end

app/helpers/kidcomments_helper.rb
module KidcommentsHelper
end

app/helpers/kids_helper.rb
module KidsHelper

  def kid_picture(kid, options = { size: 50 })
    base_path="pictures"
    image_path="#{base_path}/no_image.png"
    if !kid.picture.empty?
      image_path="#{base_path}/#{kid.picture}"
    end
    size = options[:size]
    image_tag(image_path, width: size, height: size, alt: kid.name, class: "gravatar")
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def current_user?(user)
    current_user==user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user=nil
    cookies.delete(:remember_token)   
  end

    def signed_in_user
        if !signed_in?
                store_location
                redirect_to signin_url, notice: "Please sign in."
        end
    end


end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://s.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Finding Kid", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Blackjack", blackjacks_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
		<li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<%= render partial: 'shared/feed_item', collection: @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_kid_comment_form.html.erb
<%= form_for(@kidcomment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.hidden_field :kid_id, value: @kidcomment.kid_id %>
   
    <%= f.text_area :comment, placeholder: "Add comment..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_kid_form.html.erb
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :gender %>
            <%= f.text_field :gender %>
  <!--    <%= f.select :gender, %w{Male Female}, :include_blank => true %> -->

      <%= f.label :age %>
      <%= f.text_field :age %>
 <!--      <%= f.select :age, 0..17 %> -->

       <%= f.label :time %>
      <%= f.date_select :time, start_year: 2010, end_year: Date.today.year %>

      <%= f.label :picture %>
    <%= f.text_field :picture %>

    <%= f.label :appearance, "Appearances (separated by commas)" %>
      <%= f.text_field :appearance_list %> 

    <%= f.label :place, "Places (separated by commas)" %>
      <%= f.text_field :place_list %> 

      <%= f.label :credits %>
      <%= f.text_field :credits %>

      <%= f.label :lost, "Report Lost" %>
      <%= f.check_box :lost %>

app/views/shared/_kid_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= pluralize(current_user.credit, "credit") %>

</div>

app/views/shared/_task_list.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<% @tasks.each do | current_task| %>
	    <li id="<%= current_task.name %>">
	    <%= link_to "Go to task", task_path current_task, class: "btn btn-large btn-primary" %>
	<% end %>
</li>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_user_form.html.erb
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= current_user.title %>
</span>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.kid_comments.count, "comment") %>
</span>